name: Deploy Vite app to GitHub Pages

on:
  push:
    branches:
      - SitoOnline  # Deploy automatico solo quando fai push su SitoOnline

permissions:
  contents: write
  pages: write
  id-token: write

# Consenti solo un deploy alla volta
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Deploy to SitoOnline branch
        run: |
          # Configura git
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          
          # Salva la build in una cartella temporanea
          cp -r dist ../temp-dist
          
          # Pulisce tutto tranne .git
          find . -maxdepth 1 -not -name '.git' -not -name '.' -exec rm -rf {} +
          
          # Copia la build nella root
          cp -r ../temp-dist/* .
          cp -r ../temp-dist/.* . 2>/dev/null || true
          
          # Crea .nojekyll per GitHub Pages
          touch .nojekyll
          
          # Commit e push
          git add .
          git commit -m "Deploy: $(date)" || exit 0
          git push origin SitoOnline